//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuditLog.WebService.IAuditLogService")]
    public interface IAuditLogService {
        
        // CODEGEN: Generating message contract since element name CreateSessionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuditLogService/CreateSession", ReplyAction="http://tempuri.org/IAuditLogService/CreateSessionResponse")]
        Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionResponse CreateSession(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuditLogService/CreateSession", ReplyAction="http://tempuri.org/IAuditLogService/CreateSessionResponse")]
        System.Threading.Tasks.Task<Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionResponse> CreateSessionAsync(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequest request);
        
        // CODEGEN: Generating message contract since element name application from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuditLogService/WriteEntry", ReplyAction="http://tempuri.org/IAuditLogService/WriteEntryResponse")]
        Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryResponse WriteEntry(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuditLogService/WriteEntry", ReplyAction="http://tempuri.org/IAuditLogService/WriteEntryResponse")]
        System.Threading.Tasks.Task<Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryResponse> WriteEntryAsync(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequest request);
        
        // CODEGEN: Generating message contract since element name session from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuditLogService/FinalizeSession", ReplyAction="http://tempuri.org/IAuditLogService/FinalizeSessionResponse")]
        Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionResponse FinalizeSession(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuditLogService/FinalizeSession", ReplyAction="http://tempuri.org/IAuditLogService/FinalizeSessionResponse")]
        System.Threading.Tasks.Task<Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionResponse> FinalizeSessionAsync(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateSession", Namespace="http://tempuri.org/", Order=0)]
        public Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequestBody Body;
        
        public CreateSessionRequest() {
        }
        
        public CreateSessionRequest(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateSessionRequestBody {
        
        public CreateSessionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionResponseBody Body;
        
        public CreateSessionResponse() {
        }
        
        public CreateSessionResponse(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateSessionResult;
        
        public CreateSessionResponseBody() {
        }
        
        public CreateSessionResponseBody(string CreateSessionResult) {
            this.CreateSessionResult = CreateSessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteEntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteEntry", Namespace="http://tempuri.org/", Order=0)]
        public Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequestBody Body;
        
        public WriteEntryRequest() {
        }
        
        public WriteEntryRequest(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteEntryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int level;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string application;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string session;
        
        public WriteEntryRequestBody() {
        }
        
        public WriteEntryRequestBody(int level, string application, string userid, string name, string data, string session) {
            this.level = level;
            this.application = application;
            this.userid = userid;
            this.name = name;
            this.data = data;
            this.session = session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteEntryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteEntryResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryResponseBody Body;
        
        public WriteEntryResponse() {
        }
        
        public WriteEntryResponse(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WriteEntryResponseBody {
        
        public WriteEntryResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeSession", Namespace="http://tempuri.org/", Order=0)]
        public Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequestBody Body;
        
        public FinalizeSessionRequest() {
        }
        
        public FinalizeSessionRequest(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FinalizeSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string session;
        
        public FinalizeSessionRequestBody() {
        }
        
        public FinalizeSessionRequestBody(string session) {
            this.session = session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FinalizeSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizeSessionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionResponseBody Body;
        
        public FinalizeSessionResponse() {
        }
        
        public FinalizeSessionResponse(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FinalizeSessionResponseBody {
        
        public FinalizeSessionResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuditLogServiceChannel : Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuditLogServiceClient : System.ServiceModel.ClientBase<Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService>, Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService {
        
        public AuditLogServiceClient() {
        }
        
        public AuditLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuditLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuditLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuditLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionResponse Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService.CreateSession(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequest request) {
            return base.Channel.CreateSession(request);
        }
        
        public string CreateSession() {
            Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequest inValue = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequest();
            inValue.Body = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequestBody();
            Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionResponse retVal = ((Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService)(this)).CreateSession(inValue);
            return retVal.Body.CreateSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionResponse> Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService.CreateSessionAsync(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequest request) {
            return base.Channel.CreateSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionResponse> CreateSessionAsync() {
            Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequest inValue = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequest();
            inValue.Body = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.CreateSessionRequestBody();
            return ((Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService)(this)).CreateSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryResponse Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService.WriteEntry(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequest request) {
            return base.Channel.WriteEntry(request);
        }
        
        public void WriteEntry(int level, string application, string userid, string name, string data, string session) {
            Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequest inValue = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequest();
            inValue.Body = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequestBody();
            inValue.Body.level = level;
            inValue.Body.application = application;
            inValue.Body.userid = userid;
            inValue.Body.name = name;
            inValue.Body.data = data;
            inValue.Body.session = session;
            Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryResponse retVal = ((Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService)(this)).WriteEntry(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryResponse> Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService.WriteEntryAsync(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequest request) {
            return base.Channel.WriteEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryResponse> WriteEntryAsync(int level, string application, string userid, string name, string data, string session) {
            Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequest inValue = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequest();
            inValue.Body = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.WriteEntryRequestBody();
            inValue.Body.level = level;
            inValue.Body.application = application;
            inValue.Body.userid = userid;
            inValue.Body.name = name;
            inValue.Body.data = data;
            inValue.Body.session = session;
            return ((Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService)(this)).WriteEntryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionResponse Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService.FinalizeSession(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequest request) {
            return base.Channel.FinalizeSession(request);
        }
        
        public void FinalizeSession(string session) {
            Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequest inValue = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequest();
            inValue.Body = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequestBody();
            inValue.Body.session = session;
            Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionResponse retVal = ((Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService)(this)).FinalizeSession(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionResponse> Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService.FinalizeSessionAsync(Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequest request) {
            return base.Channel.FinalizeSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionResponse> FinalizeSessionAsync(string session) {
            Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequest inValue = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequest();
            inValue.Body = new Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.FinalizeSessionRequestBody();
            inValue.Body.session = session;
            return ((Kapsch.IS.ProcessEngine.WFActivity.AuditLog.WebService.IAuditLogService)(this)).FinalizeSessionAsync(inValue);
        }
    }
}
