//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapsch.IS.EDP.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string Guid { get; set; }
        public string HistoryGuid { get; set; }
        public string CT_Guid { get; set; }
        public string EP_Guid { get; set; }
        public string P_Guid { get; set; }
        public string E_Guid { get; set; }
        public string L_Guid { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int C_ID { get; set; }
        public Nullable<int> C_EP_ID { get; set; }
        public Nullable<int> C_E_ID { get; set; }
        public Nullable<int> C_P_ID { get; set; }
        public Nullable<int> C_L_ID { get; set; }
        public int C_CT_ID { get; set; }
        public string Details { get; set; }
        public string Text { get; set; }
        public string Note { get; set; }
        public Nullable<short> Priority { get; set; }
        public bool VisiblePhone { get; set; }
        public bool VisibleKatce { get; set; }
        public bool ACDDisplay { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public System.DateTime ActiveTo { get; set; }
        public string Guid_ModifiedBy { get; set; }
        public string ModifyComment { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual Employment Employment { get; set; }
        public virtual Person Person { get; set; }
    }
}
