//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapsch.IS.EDP.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentWithPerson
    {
        public string Guid { get; set; }
        public int EP_ID { get; set; }
        public int E_ID { get; set; }
        public int P_ID { get; set; }
        public Nullable<int> L_ID { get; set; }
        public int ET_ID { get; set; }
        public int ES_ID { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> Exit { get; set; }
        public Nullable<System.DateTime> LastDay { get; set; }
        public bool Visible { get; set; }
        public string PersNr { get; set; }
        public string dpwKey { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public Nullable<System.DateTime> InsDT { get; set; }
        public string InsBY { get; set; }
        public Nullable<System.DateTime> UpdDT { get; set; }
        public string UpdBY { get; set; }
        public Nullable<System.DateTime> DelDT { get; set; }
        public string DelBY { get; set; }
        public bool Main { get; set; }
        public bool DNA_Update { get; set; }
        public bool AD_Update { get; set; }
        public Nullable<System.DateTime> Exit_Report { get; set; }
        public Nullable<int> DGT_ID { get; set; }
        public Nullable<int> Sponsor { get; set; }
        public Nullable<System.DateTime> FirstWorkDay { get; set; }
        public string Expr1 { get; set; }
        public System.DateTime Expr2 { get; set; }
        public System.DateTime Expr3 { get; set; }
        public System.DateTime Created { get; set; }
        public int Expr4 { get; set; }
        public string FamilyName { get; set; }
        public string FirstName { get; set; }
        public string Synonyms { get; set; }
        public string Sex { get; set; }
        public string DegreePrefix { get; set; }
        public string DegreeSuffix { get; set; }
        public string C128_FamilyName { get; set; }
        public string C128_FirstName { get; set; }
        public string C128_Title1 { get; set; }
        public string C128_Title2 { get; set; }
        public string UserID { get; set; }
        public string MainMail { get; set; }
        public string UnixID { get; set; }
        public bool VisiblePhone { get; set; }
        public string Expr5 { get; set; }
        public Nullable<System.DateTime> Expr6 { get; set; }
        public string Expr7 { get; set; }
        public Nullable<System.DateTime> Expr8 { get; set; }
        public string Expr9 { get; set; }
        public string Language { get; set; }
        public Nullable<bool> PictureVisible { get; set; }
        public string Display_FamilyName { get; set; }
        public string Display_FirstName { get; set; }
        public bool AD_Picture { get; set; }
        public Nullable<System.DateTime> AD_Picture_UpdDT { get; set; }
    }
}
