//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapsch.IS.EDP.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employment()
        {
            this.Account = new HashSet<Account>();
            this.Contact = new HashSet<Contact>();
            this.EmploymentAccount = new HashSet<EmploymentAccount>();
            this.GroupMember = new HashSet<GroupMember>();
            this.OrgUnitRole = new HashSet<OrgUnitRole>();
            this.ProcessEntity = new HashSet<ProcessEntity>();
            this.User = new HashSet<User>();
            this.EquipmentDefinitionOwner = new HashSet<EquipmentDefinitionOwner>();
        }
    
        public string Guid { get; set; }
        public string HistoryGuid { get; set; }
        public string P_Guid { get; set; }
        public string ET_Guid { get; set; }
        public string DGT_Guid { get; set; }
        public string ENLO_Guid { get; set; }
        public int EP_ID { get; set; }
        public int P_ID { get; set; }
        public int ET_ID { get; set; }
        public Nullable<System.DateTime> Entry { get; set; }
        public Nullable<System.DateTime> Exit { get; set; }
        public Nullable<System.DateTime> LastDay { get; set; }
        public bool Visible { get; set; }
        public string PersNr { get; set; }
        public string dpwKey { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Exit_Report { get; set; }
        public Nullable<int> DGT_ID { get; set; }
        public Nullable<int> Sponsor { get; set; }
        public string Sponsor_Guid { get; set; }
        public Nullable<System.DateTime> FirstWorkDay { get; set; }
        public byte Status { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public System.DateTime ActiveTo { get; set; }
        public string Guid_ModifiedBy { get; set; }
        public string ModifyComment { get; set; }
        public System.DateTime LeaveFrom { get; set; }
        public System.DateTime LeaveTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual DistributiongroupType DistributiongroupType { get; set; }
        public virtual EmploymentType EmploymentType { get; set; }
        public virtual EnterpriseLocation EnterpriseLocation { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmploymentAccount> EmploymentAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMember> GroupMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgUnitRole> OrgUnitRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessEntity> ProcessEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentDefinitionOwner> EquipmentDefinitionOwner { get; set; }
    }
}
