//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapsch.IS.EDP.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enterprise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enterprise()
        {
            this.Access = new HashSet<Access>();
            this.EnterpriseLocation = new HashSet<EnterpriseLocation>();
            this.OrgUnit1 = new HashSet<OrgUnit>();
        }
    
        public string Guid { get; set; }
        public string HistoryGuid { get; set; }
        public string Guid_Parent { get; set; }
        public string Guid_Root { get; set; }
        public string USDO_Guid { get; set; }
        public int E_ID { get; set; }
        public int E_ID_Parent { get; set; }
        public int E_ID_Root { get; set; }
        public string NameShort { get; set; }
        public string NameLong { get; set; }
        public string HomeIntranet { get; set; }
        public string HomeInternet { get; set; }
        public string Synonyms { get; set; }
        public string FibuNummer { get; set; }
        public string FibuGericht { get; set; }
        public string UID1 { get; set; }
        public string UID2 { get; set; }
        public string ARA { get; set; }
        public string DVR { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public Nullable<int> E_ID_new { get; set; }
        public string IntranetCOM { get; set; }
        public Nullable<int> O_ID_Dis { get; set; }
        public Nullable<int> O_ID_Prof { get; set; }
        public string O_Guid_Dis { get; set; }
        public string O_Guid_Prof { get; set; }
        public bool AD_Picture { get; set; }
        public bool HasEmployees { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public System.DateTime ActiveTo { get; set; }
        public string Guid_ModifiedBy { get; set; }
        public string ModifyComment { get; set; }
        public string DistributionEmailAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Access> Access { get; set; }
        public virtual OrgUnit OrgUnit { get; set; }
        public virtual Person Person { get; set; }
        public virtual UserDomain UserDomain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnterpriseLocation> EnterpriseLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgUnit> OrgUnit1 { get; set; }
    }
}
