//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapsch.IS.EDP.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentDefinition()
        {
            this.EquipmentDefinitionPrice = new HashSet<EquipmentDefinitionPrice>();
            this.EquipmentDefinitionOwner = new HashSet<EquipmentDefinitionOwner>();
            this.CategoryEntity = new HashSet<CategoryEntity>();
        }
    
        public string Guid { get; set; }
        public string HistoryGuid { get; set; }
        public int Q_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Config { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public System.DateTime ActiveTo { get; set; }
        public string Guid_ModifiedBy { get; set; }
        public string ModifyComment { get; set; }
        public string ClientReferenceIDForPrice { get; set; }
        public Nullable<int> ClientReferenceSystemForPrice { get; set; }
        public string WorkingInstructions { get; set; }
        public string DescriptionLong { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentDefinitionPrice> EquipmentDefinitionPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentDefinitionOwner> EquipmentDefinitionOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryEntity> CategoryEntity { get; set; }
    }
}
