//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapsch.IS.EDP.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMembers
    {
        public string Guid { get; set; }
        public string G_Guid { get; set; }
        public string EMP_Guid { get; set; }
        public int GM_ID { get; set; }
        public int G_ID { get; set; }
        public int EP_ID { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public System.DateTime Modified { get; set; }
    }
}
