//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapsch.IS.EDP.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectRelation
    {
        public string Guid { get; set; }
        public string Object1 { get; set; }
        public string Object2 { get; set; }
        public string Data { get; set; }
        public string FromTemplateGuid { get; set; }
        public byte Status { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public string HistoryGuid { get; set; }
        public string ORTYGuid { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public System.DateTime ActiveTo { get; set; }
        public string Guid_ModifiedBy { get; set; }
        public string ModifyComment { get; set; }
        public Nullable<System.DateTime> NextValidityCheckDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ObjectRelationType ObjectRelationType { get; set; }
    }
}
