//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapsch.IS.EDP.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskItems
    {
        public string Guid { get; set; }
        public string TSK_ProcessName { get; set; }
        public string TSK_TaskTitle { get; set; }
        public string TSK_EffectedPerson_UserID { get; set; }
        public string TSK_Requestor_UserID { get; set; }
        public string TSK_Approver_UserID { get; set; }
        public string TSK_ToDo { get; set; }
        public string TSK_DecisionOptions { get; set; }
        public string TSK_Information { get; set; }
        public string TSK_Notes { get; set; }
        public Nullable<System.DateTime> TSK_Duedate { get; set; }
        public Nullable<System.DateTime> TSK_DateRequested { get; set; }
        public string TSK_Decision { get; set; }
        public string TSK_LinkedTasks_ID { get; set; }
        public Nullable<System.DateTime> TSK_DateNextReminder { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
