//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapsch.IS.EDP.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskItem()
        {
            this.EntityCheck = new HashSet<EntityCheck>();
        }
    
        public string Guid { get; set; }
        public string HistoryGuid { get; set; }
        public string TSK_ProcessName { get; set; }
        public string TSK_ProcessGuid { get; set; }
        public string TSK_TaskActivityID { get; set; }
        public bool TSK_IsBulkActivity { get; set; }
        public string TSK_TaskTitle { get; set; }
        public string TSK_EffectedPerson_EmplGUID { get; set; }
        public string TSK_Requestor_EmplGUID { get; set; }
        public string TSK_Approver_EmplGUID { get; set; }
        public string TSK_ToDo { get; set; }
        public string TSK_DecisionOptions { get; set; }
        public string TSK_Information { get; set; }
        public string TSK_Notes { get; set; }
        public Nullable<System.DateTime> TSK_Duedate { get; set; }
        public Nullable<System.DateTime> TSK_DateRequested { get; set; }
        public string TSK_Decision { get; set; }
        public string TSK_LinkedTasks_ID { get; set; }
        public Nullable<System.DateTime> TSK_DateNextReminder { get; set; }
        public string TSK_Status { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public System.DateTime ActiveFrom { get; set; }
        public System.DateTime ActiveTo { get; set; }
        public string Guid_ModifiedBy { get; set; }
        public string ModifyComment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityCheck> EntityCheck { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
